In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.3.1'

In [2]:
##Creating Tensors
scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
#no of dimmentions
print(scalar.ndim)
#get tensor back as python int 
scalar.item()

0


7

In [4]:
#vector
vector=torch.tensor([7,7])
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
## MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX.ndim

2

In [7]:
MATRIX[1]

tensor([ 9, 10])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
## TENSORS
TENSORS= torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSORS

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSORS.ndim

3

In [11]:
TENSORS.shape

torch.Size([1, 3, 3])

### Random Tensors

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

"Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers"

In [12]:
# Create a random tensor of size (3,4)
random_tensor=torch.rand(2,2,2)
random_tensor

tensor([[[0.7859, 0.9065],
         [0.3311, 0.7761]],

        [[0.2771, 0.8701],
         [0.4451, 0.5855]]])

In [13]:
random_tensor[1,1,1]
# random_tensor.shape

tensor(0.5855)

In [14]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) #height , width , colour channel(R,B,G)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
## Zeros and ones
## create a tensor of all zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones= torch.ones(3,4)
ones
ones.dtype

torch.float32

In [17]:
##creating a range of tensors and tensors-like
torch.arange(0,10)
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [18]:
## creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensors Data Type

**Note:** Tensor datatype is one of the 3 big errors you will run into wiht pytorch and DL:<br>
1.Tensors not right datatype<br>
2.tensors not right shape<br>
3.tensors not on the right device

In [19]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,# what datatype is the tensor(ex: float32 or float16)
                               device=None,## cpu , gpu , cuda
                               requires_grad=False)## track the gradients
float_32_tensor

tensor([3., 6., 9.])

In [20]:
float_32_tensor.dtype

float_16_tensor = float_32_tensor.type(torch.float16)

In [21]:
float_16_tensor.dtype

torch.float16

In [22]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [23]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting informantion form tensors
<dr>
1.Tensors not right datatype - to do get datatype form a tensor,can use tensor.dtype<br>
2.tensors not right shape - to get shape from a tensor, can use tensor.shape<br>
3.tensors not on the right device - to get device from a tensor,can use tensor.device

In [24]:
# create a tensor 
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1807, 0.0838, 0.7043, 0.2714],
        [0.4324, 0.3535, 0.9288, 0.5767],
        [0.6288, 0.8822, 0.1191, 0.9837]])

In [25]:
#find out details about some tensor
print(some_tensor)
print(f"Datetype of tensor: {some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.1807, 0.0838, 0.7043, 0.2714],
        [0.4324, 0.3535, 0.9288, 0.5767],
        [0.6288, 0.8822, 0.1191, 0.9837]])
Datetype of tensor: torch.float32
shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Mainpulating tensors (tensor operation)

tensor operation includes:
* Addith=ion
* sub
* multiplication (element- wise)
* division
* matrix multiplication

In [26]:
#create tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# multi
tensor * 10

tensor([10, 20, 30])

In [28]:
# we can use pytorch in-build function
torch.mul(tensor,10)

tensor([10, 20, 30])

## matrix multiplication

Two main ways of performing multiplication in neural network and DL:

1. Element-wise multiplication
2. matrix multiplication(dot product)


In [29]:
## Element wise multi.

print(tensor,"*",tensor) 
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [30]:
## Matrix multi.

torch.matmul(tensor,tensor)

tensor(14)

There are two main rules that performing matrix multi. needs to satisfy:

1. The **inner dimensions** must match:
* (3,2) @ (3,2) won't work
* (3,2) @ (3,2)  will work
* (3,2) @ (2,3) will work

In [31]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4666, 0.2955, 0.3206],
        [0.2935, 0.2214, 0.2336],
        [0.5577, 0.1935, 0.2396]])

2. The resulting matrix has the shape of the **outer dimensions**:
* (2,3) @ (3,2) --> (2,2)
* (3,2) @ (2,3) --> (3,3)

In [32]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)).shape

torch.Size([3, 3])

one of the most common error in DL : shape errors 

In [33]:
# shapes for matrix multi.
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [34]:
# torch.mm(tensor_A,tensor_B) ## torch.mm is same as torch.matmul


In [35]:
## to fix our tensor shape issues we can use "transpose"

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [36]:
print(f"original:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"new:tensor_A={tensor_A.shape},tensor_B={tensor_B.T.shape}")
print(f"multmul:{tensor_A.shape} @ {tensor_B.shape} <- inner dimention must match")
print(f"output: ")
output= torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")



original:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
new:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([2, 3])
multmul:torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimention must match
output: 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)


In [37]:
#create a tensor 
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
# Find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [39]:
# Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [40]:
# Find the mean note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

## Finding the positional min and max

In [41]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [42]:
# Find the position in tensor that has the min value with argmin() -> return index position of target tensor where the min value occurs
x.argmin(),x[0]

(tensor(0), tensor(1))

In [43]:
# Find the position in tensor that has the max value with argmax() -> return index position of target tensor where the max value occurs
u = x.argmax()

In [44]:
x[u]

tensor(91)

## Reshaping, stacking,squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - remove all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimensions to a target tensor 
* Permute - Return a view of the input with dimensions permuted(Swapped) in a certain way


In [45]:
# Lets create a tensor

x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# Add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
y=torch.arange(21,30)
y.shape

torch.Size([9])

In [50]:
y.reshape(1,9)

tensor([[21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,y],dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [52]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [53]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [54]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [55]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [56]:
## torch.squeeze() - removes all single dimensition from a target tensor
x_reshaped.shape

torch.Size([1, 9])

In [57]:
x_squeeze=x_reshaped.squeeze()
x_reshaped.squeeze() ,x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# torch.unsqueeze() - adda a single dimension to a target tensor at a specific dim (dimension)

print(f"previous target: {x_squeeze}")
print(f"previous shape: {x_squeeze.shape}")

# add extra dimension with unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(dim=0)

print(x_unsqueeze,x_unsqueeze.shape)

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [59]:
# torch.permute - rearrange the dimensions of a target tensor in a specfied order
x = torch.rand(2,3,5)

x,x.shape

(tensor([[[0.9801, 0.0160, 0.2905, 0.7772, 0.4817],
          [0.7151, 0.9650, 0.8688, 0.8920, 0.9188],
          [0.0674, 0.9626, 0.6014, 0.0306, 0.0065]],
 
         [[0.5341, 0.3456, 0.5184, 0.3737, 0.2986],
          [0.9856, 0.4862, 0.5522, 0.1362, 0.3465],
          [0.6546, 0.3707, 0.3296, 0.8346, 0.6794]]]),
 torch.Size([2, 3, 5]))

In [60]:
y = torch.permute(x,(2,0,1))
y

tensor([[[0.9801, 0.7151, 0.0674],
         [0.5341, 0.9856, 0.6546]],

        [[0.0160, 0.9650, 0.9626],
         [0.3456, 0.4862, 0.3707]],

        [[0.2905, 0.8688, 0.6014],
         [0.5184, 0.5522, 0.3296]],

        [[0.7772, 0.8920, 0.0306],
         [0.3737, 0.1362, 0.8346]],

        [[0.4817, 0.9188, 0.0065],
         [0.2986, 0.3465, 0.6794]]])

In [61]:
y.shape

torch.Size([5, 2, 3])

In [62]:
x_original = torch.rand(224,224,3)
x_original.shape

torch.Size([224, 224, 3])

In [63]:
x_original.permute(2,0,1).shape

torch.Size([3, 224, 224])

## Indexing (selecting data from tensors)
index with pyt in similar to indexing in numpy 

In [64]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
# Let's index middle bracket
x[0][0]

tensor([1, 2, 3])

In [67]:
# Let's index on the most innner bracket (last dimension)
x[0][0][0]

tensor(1)

In [68]:
# You can also use ":" to select "all" of a target dimension
x[:,1]

tensor([[4, 5, 6]])

In [69]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
x[:,1,1]

tensor([5])

In [71]:
x[0,0,:]

tensor([1, 2, 3])

In [72]:
# Index on x to return 9

#Index on x to return 3,6,9
x[:,2,2] , x[:,:,2]

(tensor([9]), tensor([[3, 6, 9]]))

## Pytorch tensors and numpy

NUmpy is a popular scientific python numerical computing library.and because of htis , pytorch has functionality to interact with it.

* Data in NUmpy want in pytorch tensor -> torch.from_numpy(ndarray)
* pytorch tensor -> Numpy -> torch.tensor.numpy()
 

In [73]:
# Numpy array to tensor
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# array float64 ,tensor default -> float32

array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [74]:
# Change the value of array, what will this do to 'tensor'?
array = array +1

array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [75]:
#Tensor to numpy

tensor = torch.ones(7)
numpy = tensor.numpy()
tensor , numpy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
# Change the value of tensor, what will this do to 'array'?

tensor = tensor +1

numpy , tensor


(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

* start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again ....

* to reduce the randomnes in nn and pyt comes the concept of a **random seed**

essentially what the random seed does is "flavour" the randomness.

In [77]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.0349, 0.9585, 0.7021, 0.3975],
        [0.4782, 0.1368, 0.7740, 0.9745],
        [0.5098, 0.7536, 0.4598, 0.2312]])
tensor([[0.1473, 0.1104, 0.0809, 0.0977],
        [0.4815, 0.6672, 0.9479, 0.1937],
        [0.9637, 0.0702, 0.5324, 0.0611]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [78]:
# Let's make some random but reproducible tensors

#Set the random seed

RANDOM_SEED = 1
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_D = torch.rand(3,4)

print(rand_c)
print(rand_D)
print(rand_c == rand_D)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [79]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [80]:
torch.cuda.is_available()

True

In [81]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [82]:
tensor = torch.rand(1,3)
print(tensor,tensor.device)

tensor([[0.6826, 0.3051, 0.4635]]) cpu


In [83]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([[0.6826, 0.3051, 0.4635]], device='cuda:0')

In [84]:
print(tensor_gpu)

tensor([[0.6826, 0.3051, 0.4635]], device='cuda:0')


In [85]:
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([[0.6826141 , 0.3051495 , 0.46354562]], dtype=float32)